services:
  rtsp-server:
    restart: unless-stopped
    ports:
      - "1935:1935"
      - "8554:8554"
      - "8888:8888"
    environment:
      - RTSP_PROTOCOLS=tcp
    image: bluenviron/mediamtx

  rtsp-test-stream:
    restart: unless-stopped
    image: linuxserver/ffmpeg:version-4.4-cli
    links:
      - "rtsp-server:rtsp-server"
    depends_on:
      - rtsp-server
    command: -re -stream_loop -1 -i https://eu-central-1.linodeobjects.com/savant-data/demo/Free_City_Street_Footage.mp4 -c copy -bsf:v h264_mp4toannexb -f rtsp rtsp://rtsp-server:8554/test